---
- name: Yum install LDG-Client
  yum:
    name: ldg-client
    state: latest
    enablerepo: lscsoft*

- name: Yum install git and git-lfs
  yum:
    name: git-lfs
    state: latest
    enablerepo: lscsoft*

- name: Yum install pegasus
  yum:
    name: pegasus
    state: latest
    enablerepo: lscsoft*,osg

- name: Yum install Python virtualenv tools
  yum:
    name:
      - python-virtualenv
      - python34-virtualenv
      - python-virtualenvwrapper
      - python-virtualenv-clone
    state: latest
    enablerepo: lscsoft*

- name: Yum install Python pip tools
  yum:
    name:
      - python2-pip
      - python34-pip
    state: latest
    enablerepo: lscsoft*

- name: Yum install Condor tools
  yum:
    name:
      - python2-condor
      - python3-condor

- name: Yum install self management tools
  yum:
    name:
      - duc
      - fish
    state: latest
    enablerepo: lscsoft*

- name: Yum install user management tools
  yum:
    name:
      - finger
      - parallel
    state: latest
    enablerepo: lscsoft*
