---
- name: Yum install CVMFS
  yum:
    name:
      - cvmfs
      - cvmfs-x509-helper
      - cvmfs-config-default
      - osg-ca-certs

- name: Use EGI cvmfs config by default
  lineinfile:
    path:  /etc/cvmfs/default.d/60-egi.conf
    regexp: '^CVMFS_CONFIG_REPOSITORY=config-egi.egi.eu'
    line: 'CVMFS_CONFIG_REPOSITORY=config-egi.egi.eu'

- name: Enable AutoFS for cvmfs
  lineinfile:
    path:  /etc/auto.master
    line: '/cvmfs /etc/auto.cvmfs'

- name: Start AutoFS
  systemd:
    state: started
    name: autofs
    enabled: yes

- name: Copy default CVMFS config
  template:
    src: default.local.j2
    dest: /etc/cvmfs/default.local
    owner: root
    group: root
    mode: 0644

- name: Copy osgstorage config
  template:
    src: osgstorage.org.local.j2
    dest: /etc/cvmfs/domain.d/osgstorage.org.local
    owner: root
    group: root
    mode: 0644

- name: Copy ligo.osgstorage.org.conf
  template:
    src: ligo.osgstorage.org.local.j2
    dest: /etc/cvmfs/config.d/ligo.osgstorage.org.conf
    owner: root
    group: root
    mode: 0644

- name: Copy gwosc.osgstorage.org.conf
  template:
    src: gwosc.osgstorage.org.local.j2
    dest: /etc/cvmfs/config.d/gwosc.osgstorage.org.conf
    owner: root
    group: root
    mode: 0644
