stages:
  - Lint

variables:
  PIP_CACHE_DIR: "${CI_PROJECT_DIR}/.cache/pip"

cache:
  key: "${CI_JOB_NAME}"
  paths:
    - .cache/pip

lint:
  stage: Lint
  image: python
  needs: []
  before_script:
    - python -m pip install
          ansible-lint
          ansible-lint-junit
  script:
    - ansible-lint | tee ansible-lint.txt
  after_script:
    - ansible-lint-junit ansible-lint.txt -o ansible-lint.xml
  artifacts:
    expire_in: 1month
    reports:
      junit: ansible-lint.xml
    when: always
