---

- block:

  - name: disable selinux
    selinux:
      state: disabled

  - name: install yum-utils
    yum:
      name: yum-utils
      state: installed

  - name: Disable repos
    command: yum-config-manager --disable \*

  - name: Disable repos
    command: yum-config-manager --add-repo https://yumrepo.nautilus.optiputer.net/nautilus.repo

    # Stanza to set MTU to 9000 on 10 gig needed here

  - name: install node packages - i (non-gpu)
    yum:
      name: {{ item }}
      state: installed
    with_items:
      - wget
      - pciutils
      - mlocate
      - net-tools
      - nmap
      - htop
      - gdisk
      - nfs-utils
      - kernel-devel
      - ntp

  # NetworkManager dealt with in kickstart
  - name: disable chronyd service
    systemd:
      name: chronyd
      state: stopped
      enabled: 'no'

  - name: enable ntpd service
    systemd:
      name: ntpd
      state: started
      enabled: 'yes'

  - name: yum clean all
    command: yum clean all

  - name: install node packages - ib (non-gpu)
    yum:
      name: {{ item }}
      state: installed
    with_items:
      - kernel-ml
      - kernel-ml-devel

  - name: edit grub
    command: sed -i 's/rhgb/rhgb/transparent_hugepage=never/' /etc/default/grub

  - name: run package-cleanup
    command: package-cleanup --oldkernels --count=1

  # REBOOT is here in doc

  # NON GPU section from doc

  - name: install node packages - ii (non-gpu)
    yum:
      name: {{ item }}
      state: installed
    with_items:
      - device-mapper-persistent-data
      - lvm2
      - wget

  - name: Add repository for docker
    command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

  - name: install docker-ce
    yum:
      name: docker-ce
      state: installed

  - name: Download and write k8s.conf
    get_url:
      url: https://gitlab.nautilus.optiputer.net/prp/kernel/raw/master/k8s.conf
      dest: /etc/sysctl.d/k8s.conf

  - name: sysctl --system
    command: sysctl --system

  - name: systemctl daemon-reload
    command: systemctl daemon-reload

  - name: enable and restart docker
    systemd:
      name: docker
      state: restarted
      enabled: 'yes'

   # Add stanza to do kubernetes repo file here

   # Fail2bn handled in seperate role

  become: 'True'
...
