---
# Ansible common tasks to install LIGO Servers at Cardiff
#
# Copyright (C) 2019  Paul Hopkins <HopkinsP@cardiff.ac.uk>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License,
# Version 2.1 only as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#

- name: Yum install yum-priorities plugin
  yum: name=yum-plugin-priorities
  when: "'ligo_servers' in group_names"

- name: Add LSCSoft Production repo
  yum_repository:
    name: lscsoft-production
    description: lscsoft-production
    baseurl: http://arccadeploy.cf.ac.uk/cobbler/repo_mirror/LIGO_lscsoft-production_x86_64/
    gpgcheck: no
  when: "'ligo_servers' in group_names"

- name: Add LSCSoft Backports repo
  yum_repository:
    name: lscsoft-backports
    description: lscsoft-backports
    baseurl: http://cl8/software/lscsoft/7/backports/
    priority: 97
    gpgcheck: no
  when: "'ligo_servers' in group_names"

- name: Add EPEL GPG key
  rpm_key:
    key: http://cl8/software/RPM-GPG-KEY-EPEL-7
  when: "'ligo_everything' in group_names"

- name: Add LSCSoft EPEL repo
  yum_repository:
    name: lscsoft-epel
    description: lscsoft-epel
    baseurl: http://arccadeploy.cf.ac.uk/cobbler/repo_mirror/LIGO_EPEL7_x86_64/
  when: "'ligo_everything' in group_names"

- name: Add HTCondor GPG key
  rpm_key:
    key: http://cl8/software/GPG-KEY-HTCondor
  when: "'ligo_everything' in group_names"

- name: Add HTCondor Stable repo
  yum_repository:
    name: htcondor-stable
    description: HTCondor Stable RPM Repository for Redhat Enterprise Linux 7
    file: htcondor
    baseurl: http://arccadeploy.cf.ac.uk/cobbler/repo_mirror/LIGO_htcondor-stable_x86_64/
    priority: 96
  when: "'ligo_everything' in group_names"

#- name: Add HTCondor Development repo
#  yum_repository:
#    name: htcondor-development
#    description: HTCondor Development RPM Repository for Redhat Enterprise Linux 7
#    file: htcondor
#    baseurl: http://cl8/software/htcondor/development/8.8/rhel7/
#    priority: 96
#    enabled: no

- name: Add HTCondor Prerelease repo
  yum_repository:
    name: htcondor-prerelease
    description: HTCondor Prerelease RPM Repository for Redhat Enterprise Linux 7
    file: htcondor
    baseurl: http://arccadeploy.cf.ac.uk/cobbler/repo_mirror/LIGO_htcondor-prerelease_x86_64/
    priority: 96
    enabled: no
  when: "'ligo_everything' in group_names"

#- name: Add HTCondor Testing repo
#  yum_repository:
#    name: htcondor-testing
#    description: HTCondor Testing RPM Repository for Redhat Enterprise Linux 7
#    file: htcondor
#    baseurl: http://cl8/software/htcondor/testing/8.8/rhel7/
#    priority: 96
#    enabled: no

- name: Add OSG GPG key
  rpm_key:
    key: http://cl8/software/RPM-GPG-KEY-OSG
  when: "'ligo_everything' in group_names"

- name: Add OSG Stable repo
  yum_repository:
    name: osg
    description: OSG Stable
    file: osg
    baseurl: http://arccadeploy.cf.ac.uk/cobbler/repo_mirror/LIGO_osg-stable_x86_64/
    gpgkey: http://cl8/software/RPM-GPG-KEY-OSG
    exclude: cvmfs condor*
    priority: 97
  when: "'ligo_everything' in group_names"

#- name: Add Osg Development repo
#  yum_repository:
#    name: osg-development
#    description: Osg Development
#    file: osg
#    baseurl: http://cl8/software/osg/3.4/development
#    priority: 97
#    enabled: no

- name: Add CVMFS GPG key
  rpm_key:
    key: http://cl8/software/GPG-KEY-cernvm
  when: "'ligo_everything' in group_names"

- name: Add CVMFS repo
  yum_repository:
    name: cvmfs
    description: CVMFS
    baseurl: http://arccadeploy.cf.ac.uk/cobbler/repo_mirror/LIGO_cvmfs_x86_64/
    gpgkey: http://cl8/software/GPG-KEY-cernvm
    priority: 96
  when: "'ligo_everything' in group_names"

- name: Add Shibboleth Repo
  yum_repository:
    name: shibboleth
    description: Shibboleth (CentOS_7)
    baseurl: http://cl8/software/shibboleth/7
    gpgkey: http://cl8/software/GPG-KEY-shibboleth
    enabled: yes
  when: "'ligo_servers' in group_names"
