---
- name: Yum install dependencies
  yum:
    name:
      - httpd
      - mod_ssl
    state: latest
    enablerepo: lscsoft*

# TODO SET HOSTNAME
# ServerName www.example.com:80

- name: create challenge directory
  file:
    path: /var/www/html/.well-known/acme-challenge
    state: directory
    owner: root
    group: root
    mode: "0755"
  tags: letsencrypt

# Do this manually because LIGO group is in LDAP,
# and just using "usermod" does not work
# Also add Jupyterhub group, for use later
- name: Add apache user to LIGO
  lineinfile:
    path: /etc/group
    line: "LIGO:x:6000005:apache,jupyterhub"

- name: yum install shibboleth
  yum:
    name:
      - shibboleth
    state: latest
    enablerepo: shibboleth
  tags: shibboleth

- name: create challenge directory
  file:
    path: /root/bin
    state: directory
    owner: root
    group: root
    mode: "0750"

- name: install getssl tool
  get_url:
    url: https://raw.githubusercontent.com/srvrco/getssl/master/getssl
    dest: /root/bin/getssl
    mode: "0700"
  tags: letsencrypt

- name: Create getssl config
  command: /root/bin/getssl -c ligo.gravity.cf.ac.uk
  args:
    creates: /root/.getssl/getssl.cfg

# Now edit getssl config
# Or alternatively use this role: https://github.com/geerlingguy/ansible-role-certbot

- name: Create getssl cronjob
  cron:
    name: getssl
    cron_file: getssl
    minute: "23"
    hour: "5"
    user: root
    job: '/root/bin/getssl -u -a -q 2>&1 | mail -Es "GetSSL Error Output from ligo.gravity.cf.ac.uk" cardiff-ligo-cluster-admins@cf.onmicrosoft.com'

- name: Copy selfsigned cert
  copy:
    src: selfsignedcert.pem
    dest: /etc/shibboleth/sp-cert.pem
    owner: shibd
    group: shibd
    mode: "0644"
  tags: shibboleth
  notify: restart shibd

- name: Copy selfsigned key
  copy:
    src: selfsignedkey.pem
    dest: /etc/shibboleth/sp-key.pem
    owner: shibd
    group: shibd
    mode: "0600"
  tags: shibboleth
  notify: restart shibd

- name: Copy shibboleth files
  copy:
    src: "{{ item }}"
    dest: "/etc/shibboleth/{{ item }}"
    mode: "0644"
  with_items:
    - login.ligo.org.cert.LIGOCA.pem
    - attribute-map.xml
  tags: shibboleth
  notify: reload shibd

- name: Copy shibboleth2.xml
  template:
    src: shibboleth2.xml.j2
    dest: /etc/shibboleth/shibboleth2.xml
    owner: root
    group: root
    mode: "0644"
  tags: shibboleth
  notify: reload shibd

- name: create static shibboleth discover service
  file:
    path: /srv/shibboleth-ds/
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Copy static shibboleth discovery service files
  copy:
    src: "static_ds/{{ item }}"
    dest: "/srv/shibboleth-ds/{{ item }}"
    mode: "0644"
  with_items:
    - index.html
    - idpselect.css
    - kagra.png
    - ligo.png

- name: Copy httpd shibboleth-ds conf
  template:
    src: httpd_shibboleth-ds.conf.j2
    dest: /etc/httpd/conf.d/shibboleth-ds.conf
    owner: root
    group: root
    mode: "0644"
  notify: reload httpd

- name: Copy httpd userdir.conf
  template:
    src: httpd_userdir.conf.j2
    dest: /etc/httpd/conf.d/userdir.conf
    owner: root
    group: root
    mode: "0644"
  notify: reload httpd

- name: Copy httpd https.conf
  template:
    src: httpd_https.conf.j2
    dest: /etc/httpd/conf.d/https.conf
    owner: root
    group: root
    mode: "0644"
  notify: reload httpd

- name: create secure directory
  file:
    path: /var/www/html/secure
    state: directory
    owner: root
    group: root
    mode: "0755"
  tags: httpd

- name: Start shibd
  systemd:
    name: shibd
    state: started
  tags: shibboleth
