---
- name: Install text editors
  yum:
    name:
      - vim
      - emacs
    state: latest 
  become: "True"
- name: Install development tools
  yum:
    name:
      - make
      - wget
      - git
      - zip
      - unzip
    state: latest
  become: "True"
