# 
- name: Copy limits.sh script
  template:
    src: limits.sh.j2
    dest: /etc/security/limits.sh
    owner: root
    group: root
    mode: "0755"

- name: Insert security limits after systemd rule
  pamd:
    name: "{{ item }}"
    type: "session"
    control: optional
    module_path: pam_systemd.so
    new_type: session
    new_control: optional
    new_module_path: pam_exec.so
    module_arguments: "type=open_session /etc/security/limits.sh"
    state: after
  with_items:
    - system-auth-ac
    - password-auth-ac
