---
- name: install fail2ban
  yum:
   name: fail2ban
   state: present
  become: 'True'

# Add standard jail
- name: Add fail2ban jail.local
  template:
   src: jail.local.j2
   dest: /etc/fail2ban/jail.local
   owner: root
   group: root
   mode: "0644"
   backup: yes
  notify:
   - restart fail2ban
  become: 'True'

# Add standard jail
- name: Add fail2ban sshd.local
  template:
   src: sshd.conf.j2
   dest: /etc/fail2ban/filter.d/sshd.conf
   owner: root
   group: root
   mode: "0644"
   backup: yes
  notify:
   - restart fail2ban
  become: 'True'

...
