---
- name: Create a temporary directory to work in
  tempfile:
    state: directory
    suffix: ligo_guide
  register: ligo_guide_tmpdir

- name: Download the latest version of the guide
  get_url:
    url: "https://git.cardiff.ac.uk/api/v4/projects/spxdmm%2Fligo-hawk-guide/jobs/artifacts/master/download?job=build"
    dest: "{{ ligo_guide_tmpdir.path }}/guide.zip"
    headers:
      Private-Token: "dRQAtcLvdeRkhJDYQQMh"
  when: ligo_guide_tmpdir.path is defined

- name: Extract the site zip
  unarchive:
    src: "{{ ligo_guide_tmpdir.path }}/guide.zip"
    dest: "{{ ligo_guide_tmpdir.path }}"
    remote_src: yes
  when: ligo_guide_tmpdir.path is defined

- name: Copy the site into place
  synchronize:
    src: "{{ ligo_guide_tmpdir.path }}/site/"
    dest: "/srv/guide"
  delegate_to: "{{ inventory_hostname }}"
  when: ligo_guide_tmpdir.path is defined

- name: Copy guide httpd conf
  template:
    src: "guide_httpd.conf.j2"
    dest: "/etc/httpd/conf.d/guide.conf"
    mode: "0644"

- name: Remove the temporary directory
  file:
    path: "{{ ligo_guide_tmpdir.path }}"
    state: absent
  when: ligo_guide_tmpdir.path is defined
