- name: Copy home backup script and cron command
  copy:
    src: "{{ item }}"
    dest: "/root/bin/{{ item }}"
    owner: root
    mode: '0755'
  with_items:
    - home_backup.sh
    - home_backup_cron.sh

- name: Copy rsnapshot user config
  copy:
    src: rsnapshot_by_user.conf
    dest: /etc/rsnapshot_by_user.conf
    owner: root
    mode: '0644'

- name: Create semiweekly cron job
  cron:
    name: home_backup-semiweekly
    minute: 0
    hour: 0
    weekday: "3,6"
    user: root
    job: "/root/bin/home_backup_cron.sh semiweekly"
    cron_file: home_backup

- name: Create weekly cron job
  cron:
    name: home_backup-weekly
    minute: 0
    hour: 0
    weekday: 0
    user: root
    job: "/root/bin/home_backup_cron.sh weekly"
    cron_file: home_backup

- name: Create monthly cron job
  cron:
    name: home_backup-monthly
    minute: 0
    hour: 0
    day: "1-7"
    user: root
    job: '[ "$(date +\%a )" = "Mon" ] && /root/bin/home_backup_cron.sh monthly'
    cron_file: home_backup
