---
- name: install fail2ban
  yum:
   name: fail2ban
   state: present
  become: 'True'

# Add standard jail
- name: Add fail2ban sshd.local
  template:
   src: sshd.local
   dest: /etc/fail2ban/jail.d/sshd.local
   owner: root
   group: root
   mode: "u=rw,g=r,o=r"
  notify:
   - restart fail2ban
  become: 'True'

...
