---

- name: Upgrade pip
  pip:
    name: pip
    extra_args: --upgrade

- name: Install bash_kernel package and dependencies
  pip:
    name:
      - bash_kernel
      - jupyter_client
      - ipython
      - ipykernel

- name: Install the bash_kernel
  command: "python -m bash_kernel.install"
