---
- name: install jupyterhub deps
  yum: name={{ item }} state=installed
  with_items:
      - npm
      - nodejs

# If you require printing notebooks I suggest that you install texlive
# using a role like this https://github.com/y-yu/ansible-texlive

# Jupyterhub sudo group needed for sudospawner
- name: Create Jupyterhub group
  group:
      name={{ server_sudo_group }}
      state=present

- name: Create Jupyterhub user
  user:
      name={{ server_user }}
      comment="jupyterhub server user"
      system="yes"
      state=present
      createhome="no"
      shell=/sbin/nologin
      groups={{ server_sudo_group }}

- name: Copy jupyterhub sudoers file
  template: src=jupyterhub.sudofile.j2
            dest=/etc/sudoers.d/jupyterhub
            owner=root
            group=root
            mode="u=rw,g=r,o=r"

# - name: Copy jupyter install script over
#   template: src=install-jupyterhub.sh.j2
#             dest=/root/install-jupyterhub.sh
#             owner=root
#             group=root
#             mode="u=rwx"
#
#  - name: Copy jupyterhub sudospawner install script
#    template: src=install-jh-sudospawner.sh.j2
#              dest=/root/install-jh-sudospawner.sh
#              owner=root
#              group=root
#              mode="u=rwx"
#
#  - name: Git clone sudospawner
#    git: repo='https://github.com/jupyterhub/sudospawner.git'
#         dest='{{ sudospawn_clone_dir }}'
#         version='{{ sudospawner_ver }}'
#
#  - name: Run jupyter install script - installs Py2 and Py3 kernels
#    shell: /root/install-jupyterhub.sh
#           creates=/opt/anaconda/bin/jupyterhub

#  - name: Run jupyterhub sudospawner install script
#    shell: /root/install-jh-sudospawner.sh 2&> /tmp/install-jupyterhub-sudospawner.log
#
##  - include: R-kernel.yml
##  - include: bash-kernel.yml
#

# Install extra packages into Conda environment
# Install kernerls into here: /usr/local/share/jupyter/kernels/

- name: Copy Jupyter config file over
  template: src=jupyterhub_config.py.j2
            dest='{{ working_directory }}/jupyterhub_config.py'
            owner={{ server_user }}
            group=root
            mode="u=rw,g=r,o=r"

- name: Copy Jupyter sudospawner config file over
  template: src=sudospawner-singleuser.j2
            dest=/opt/miniconda3/bin/sudospawner-singleuser
            owner=root
            group=root
            mode="u=rwx,g=rx,o=rx"

- name: Copy systemd service file over
  template: src=jupyterhub.service.j2
            dest=/lib/systemd/system/jupyterhub.service
            owner=root
            group=root
            mode="u=rwx,g=r,o=r"

- name: Copy jupyter httpd conf
  template:
    src=jupyterhub_httpd.conf.j2
    dest=/etc/httpd/conf.d/jupyter.conf
    owner=root
    group=root
    mode="0644"

- name: Copy jupyter kernels
  copy:
    src: kernels
    dest: /usr/local/share/jupyter/
    owner: root
    group: root
    mode: 'preserve'

- name: start jupyterhub service
  service: name=jupyterhub
           state=started
           enabled=yes
