---
- name: Yum install HTCondor, Facter and Ruby
  yum:
    name:
      - condor
      - facter
      - ruby
    enablerepo:
      - htcondor-stable

- name: Copy base HTCondor config file
  template:
    src: "0-common.conf.j2"
    dest: /etc/condor/config.d/0-common.conf
    owner: condor
    group: condor
    mode: 0644

- name: Remove 000-common.conf file
  file:
    path: /etc/condor/config.d/000-common.conf
    state: absent

- name: Copy Submit config.d files
  template:
    src: "submit/{{ item }}.j2"
    dest: /etc/condor/config.d/{{ item }}
    owner: condor
    group: condor
    mode: 0644
  with_items:
    - 00-role.conf
    - 01-security.conf
    - 02-admin.conf
    - 03-accounting.conf
    - 04-dagman.conf
    - 05-jobs.conf
    - 06-logs.conf
    - 07-transfers.conf
    - 08-premption.conf
    - 10-requirements.conf
    - 11-negotiator.conf
    - 20-gpu-attributes.conf
    - 52-singularity.conf
  when: "'ligo_login' in group_names"

- name: Copy Compute config.d files
  template:
    src: "execute/{{ item }}.j2"
    dest: /etc/condor/config.d/{{ item }}
    owner: condor
    group: condor
    mode: 0644
  with_items:
    - 00-role.conf
    - 40-gpu.conf
    - 50-slot.conf
    - 51-facter.conf
    - 52-singularity.conf
    - 60-job-memory.conf
  when: "'ligo_all_nodes' in group_names"

- name: Copy facter script
  template:
    src: "bin/facter_classad"
    dest: /usr/local/bin/
    owner: condor
    group: condor
    mode: 0755

- name: Disable HTCondor from starting automatically on all nodes
  systemd:
    name: condor
    enabled: no

- name: Enable Hyperthreading on all LIGO nodes
  systemd:
    name: ht-off
    enabled: no

- name: Copy accounting tags and users scripts
  copy:
    src: "{{ item }}"
    dest: /usr/local/bin/{{ item }}
    mode: '0755'
  when: "'ligo_login' in group_names"
  with_items:
    - condor_accounting_users
    - condor_accounting_tags

# Need to workout when the valid_users and valid_tags files change and then reload condor
# Perhaps with a daily cron job, but I haven't done it very regularly
- name: Generate HTCondor valid users
  command: /usr/local/bin/condor_accounting_users -s cdf -f /etc/condor/accounting/valid_users
  # args:
  #   creates: /etc/condor/accounting/valid_users
  when: "'ligo_login' in group_names"

- name: Generate HTCondor valid tags
  command: /usr/local/bin/condor_accounting_tags -r '^aluk\.(dev|prod|sim)\.(s6|o1|o2|o3|o4)\.(burst|cbc|cw|detchar|sgwb)\..+' -f /etc/condor/accounting/valid_tags
  # args:
  #   creates: /etc/condor/accounting/valid_tags
  when: "'ligo_login' in group_names"

- name: Copy ldg-report script
  copy:
    src: ldg-report
    dest: /usr/local/bin/ldg-report
    mode: '0755'
  when: "'ligo_login' in group_names"

- name: Create ldg-report httpd directory
  file:
    path="{{ ldg_report_dir }}"
    state=directory
    owner=root
    group=root
    mode="755"
  when: "'ligo_login' in group_names"

- name: Create an ldg-report cron.d file
  cron:
    name: ldg-report
    minute: 0
    hour: 2
    user: root
    job: "/usr/local/bin/ldg-report --cluster {{ ldg_cluster_name }} | sort > {{ ldg_report_dir }}/{{ ldg_cluster_name }}_$(date --utc +\\%F --date='1 day ago').txt"
    cron_file: ldg-report
  when: "'ligo_login' in group_names"

- name: Copy ldg-report httpd conf
  template:
    src=httpd_ldg-report.conf.j2
    dest=/etc/httpd/conf.d/ldg-report.conf
    owner=root
    group=root
    mode="0644"
  notify: reload httpd
  when: "'ligo_login' in group_names"

- name: Copy check_x509_expiry script
  copy:
    src: check_x509_expiry.sh
    dest: /usr/local/bin/check_x509_expiry.sh
    mode: '0755'
  when: "'ligo_login' in group_names"

- name: Create an check_x509_expiry cron.d file
  cron:
    name: check_x509_expiry
    special_time: daily
    user: root
    job: /usr/local/bin/check_x509_expiry.sh
    cron_file: check_x509_expiry
  when: "'ligo_login' in group_names"

- name: Copy parallel_nodes_orchestrator.py script
  copy:
    src: parallel_nodes_orchestrator.py
    dest: /usr/local/bin/parallel_nodes_orchestrator.py
    mode: '0755'
  when: "'ligo_login' in group_names"

- name: Create an parallel_nodes_orchestrator.py cron.d file
  cron:
    name: parallel_nodes_orchestrator
    minute: 0
    hour: 6-16
    weekday: 1-5
    user: root
    job: /usr/local/bin/parallel_nodes_orchestrator.py
    cron_file: parallel_nodes_orchestrator
  when: "'ligo_login' in group_names"
