---
- name: Yum install HTCondor
  yum:
    name:
      - condor
      - facter

- name: Copy base HTCondor config file
  template:
    src: "condor_config.j2"
    dest: /etc/condor/condor_config
    owner: condor
    group: condor
    mode: 0644
  notify:
    - Reload config

- name: Copy HTCondor config.d files
  template:
    src: "submit/{{ item }}.j2"
    dest: /etc/condor/config.d/{{ item }}
    owner: condor
    group: condor
    mode: 0644
  with_items:
    - 00-role.conf
    - 01-security.conf
    - 02-admin.conf
    - 03-accounting.conf
    - 04-dagman.conf
    - 05-jobs.conf
    - 06-logs.conf
    - 07-transfers.conf
  when: "'ligo_login' in group_names"
  notify:
    - Reload config

- name: Copy HTCondor config.d files
  template:
    src: "execute/{{ item }}.j2"
    dest: /etc/condor/config.d/{{ item }}
    owner: condor
    group: condor
    mode: 0644
  with_items:
    - 00-role.conf
    - 50-slot.conf
    - 51-facter.conf
    - 52-singularity.conf
  when: "'ligo_all_nodes' in group_names"
  notify:
    - Reload config

- name: Copy HTCondor config.d files
  template:
    src: "execute/{{ item }}.j2"
    dest: /etc/condor/config.d/{{ item }}
    owner: condor
    group: condor
    mode: 0644
  with_items:
    - 40-gpu.conf
  when: "'ligo_gpu' in group_names"
  notify:
    - Reload config

- name: Copy facter script
  template:
    src: "bin/facter_classad"
    dest: /usr/local/bin/
    owner: condor
    group: condor
    mode: 0755
  when: "'ligo_all_nodes' in group_names"

- name: Start HTCondor
  systemd:
    state: started
    name: condor
    enabled: yes

